### ISSUE TITLE
Request: Merchant without GM on the scene

### ISSUE THREAD

**Issue by GeraltBialyWilk** [SvenWerlen/fvtt-loot-sheet-npc-pf1#24]
Hi! 

Would it be possible to have a Merchant sheet working without a GM on the same scene/offline?

**Comment by SvenWerlen** [comment]
My implementation relies on DnD5 LootSheet. I don't think that it's possible because some actions are actually sending requests to the GM and are executed by the GM. If the GM is not on the scene or offline, these actions won't work. It has to be implemented that way because users don't have permissions on the LootSheet and FVTT won't let them execute actions.
